### PR TITLE
Various fixes

### PR DESCRIPTION
**Pull request by Edivad99**
- Fixed server start
- Removed RailcraftDist, it is a bad practice that is no longer used from 1.12 onwards.
- Created a packege setup that will contain all the methods needed for the events. This is to reduce the Railcraft class
- Created DecorativeTab to be equal to 1.12
- Removed copper ingot and nugget, it's already presents in vanilla
- Used a new structure called ColorMap which takes care of managing the colors of the various blocks, thus reducing the code
- Lang datagen
- Added iron and steel plates (Useful for getting started with recipes)

### CODE REVIEW

**Comment by josephtarbit** [comment]
I’d like to keep `ClientDist` the way it was - there’s no real reason to separate client setup and client events.

**Comment by Edivad99** [comment]
> I’d like to keep `ClientDist` the way it was - there’s no real reason to separate client setup and client events.

Okay, I try to fix it in a better way

**Comment by Edivad99** [comment]
> I’d like to keep `ClientDist` the way it was - there’s no real reason to separate client setup and client events.

For me it would be better to leave the two separate classes as they use two different ModBus. Leaving it as it is, we leave it to Forge to instantiate classes whenever he wants.

**Comment by Edivad99** [comment]
This PR is getting too big, I'd rather open a new PR with just the recipes.
This PR for me can be merged

**Pull request merged**
