### PR TITLE
fixed raw metals

### LINKED ISSUE #136: Raw Metal localized in en_us incorrectly.
I believe there are some misnamed items in the en_us localization:
- [Lead Raw](https://github.com/railcraft-reborn/railcraft/blob/a7e033473cda58b74dd6852c316f26ae6b807e69/src/generated/resources/assets/railcraft/lang/en_us.json#L551C1-L551C1) (Line 551)
- [Nickel Raw](https://github.com/railcraft-reborn/railcraft/blob/a7e033473cda58b74dd6852c316f26ae6b807e69/src/generated/resources/assets/railcraft/lang/en_us.json#L559C1-L559C45) (Line 559)
- [Silver Raw](https://github.com/railcraft-reborn/railcraft/blob/a7e033473cda58b74dd6852c316f26ae6b807e69/src/generated/resources/assets/railcraft/lang/en_us.json#L583) (Line 583)
- [Tin Raw](https://github.com/railcraft-reborn/railcraft/blob/a7e033473cda58b74dd6852c316f26ae6b807e69/src/generated/resources/assets/railcraft/lang/en_us.json#L616) (Line 616)
- [Zinc Raw](https://github.com/railcraft-reborn/railcraft/blob/a7e033473cda58b74dd6852c316f26ae6b807e69/src/generated/resources/assets/railcraft/lang/en_us.json#L637C31-L637C39) (Line 637)

Instead they should be named:
- **Raw Lead** (Line 551)
`"item.railcraft.lead_raw": "Lead Raw",` (Current)
`"item.railcraft.lead_raw": "Raw Lead",` (Changed)
- **Raw Nickel** (Line 559)
`"item.railcraft.nickel_raw": "Nickel Raw",` (Current)
`"item.railcraft.nickel_raw": "Raw Nickel",` (Changed)
- **Raw Silver** (Line 583)
`"item.railcraft.silver_raw": "Silver Raw",` (Current)
`"item.railcraft.silver_raw": "Raw Silver",` (Changed)
- **Raw Tin** (Line 616)
`"item.railcraft.tin_raw": "Tin Raw",` (Current)
`"item.railcraft.tin_raw": "Raw Tin",` (Changed)
- **Raw Zinc** (Line 637)
`"item.railcraft.zinc_raw": "Zinc Raw",` (Current)
`"item.railcraft.zinc_raw": "Raw Zinc",` (Changed)

### PR DESCRIPTION
**Pull request by specCon18**
**The Issue**
issue #136
 
**The Proposal**
I am presenting a fix to my earlier posted  the solution is the same thing proposed in the issue just swap the generated language lines with the proper format. (adjective then noun, not noun then adjective.)

**Possible Side Effects**
None this is just a localization fix.
 
**Alternatives**
There really isn't any other than fixing English.

### CODE REVIEW

**Comment by Edivad99** [comment]
Okay, but you need to generate them via datagen.
You need to change the translations in this section:
https://github.com/railcraft-reborn/railcraft/blob/a7e033473cda58b74dd6852c316f26ae6b807e69/src/main/java/mods/railcraft/data/RailcraftLanguageProvider.java#L246
And then run the `gradle runData` task

**Comment by specCon18** [comment]
Those Changes have been made. sorry been since 1.7 when I touched modding, still knocking the rust off.

**Comment by specCon18** [comment]
forgot the to run gradle command running now.

**Comment by specCon18** [comment]
I ran `gradle runData` as requested and had a build success though it seems that only a .cache file in generated was created i'm kinda new to all of this, haven't touched modding since 1.4.7.

**Comment by Edivad99** [comment]
Thanks!

**Pull request merged**
